---
name: plants-api

# This configuration is for testing and is insecure

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: local_dev/Dockerfile
    command: start-app
    working_dir: /app/plants_api
    develop:
      watch:
        - action: sync
          path: ../plants_api/ # host machine
          target: /app/plants_api/ # container
          ignore:
            - __pycache__
        - action: sync
          path: ../tests/ # host machine
          target: /app/tests/ # container
          ignore:
            - __pycache__
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENVIRONMENT: DEV
      CONTAINER: true

    ports:
      - target: 8000 # container
        published: 8001 # host machine
        protocol: tcp
        mode: host
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: bitnami/postgresql:latest
    restart: always
    user: "1001:0" # Colima won't mount the data directory without this
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: app
    healthcheck:
      test:
        - CMD
        - pg_isready
        - --dbname=app
        - --quiet
        - --username=postgres
      interval: 15s
      timeout: 5s
      retries: 6
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - type: bind
        source: "./db/data"
        target: "/var/lib/postgres/data"
        read_only: false
      # - ./db/data:/var/lib/postgresql/data
      - ./db:/bitnami/postgresql
    #   I think it's trying to change the ownership of my host /var/lib/postgresql/data - not sure why
    #   - ./db/entrypoint:/docker-entrypoint-initdb.d

# volumes:
#   db:
#     driver: local
